version: '3'
services:
  myapi:
    build:
      dockerfile: Dockerfile
      context: .
    image: python:3.9
    links: 
      - mongo-db
    ports: 
      - "8888:8888"
    command: bash -c "
      uvicorn main:app
      --host 0.0.0.0 --port 8888
      --reload
      "
    depends_on: 
      - mongo-db
    networks:
      - mynetwork

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    ports: 
      - "27017:27017"
    command:
      mongod --quiet --logpath /dev/null
    networks:
      - mynetwork
    volumes:
      - mongodb:/data/db

networks:
  mynetwork:

volumes:
  mongodb: